#!/usr/bin/env node
/**
 * Render standalone graphical-code-graph HTML pages.
 *
 * Usage:
 *   node strategy/graphs/engine/render.mjs
 *   node strategy/graphs/engine/render.mjs strategy/graphs/data/foo.json
 *
 * Each data file becomes strategy/graphs/<id>.html with styles, runtime,
 * and graph JSON inlined. No external network or runtime dependencies.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const engineDir = path.dirname(fileURLToPath(import.meta.url));
const graphsDir = path.resolve(engineDir, "..");
const dataDir = path.join(graphsDir, "data");
const styles = fs.readFileSync(path.join(engineDir, "styles.css"), "utf8");
const runtime = fs.readFileSync(path.join(engineDir, "runtime.js"), "utf8");

function htmlPage(graph) {
    const json = JSON.stringify(graph).replace(/</g, "\\u003c");
    const title = graph.title || "Code graph";
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<!-- Generated by strategy/graphs/engine/render.mjs. Edit the JSON in data/, then re-run the renderer. -->
<style>
${styles}
</style>
</head>
<body>
<div id="graph"></div>
<script>
window.GRAPHICAL_CODE_GRAPH = ${json};
</script>
<script>
${runtime}
</script>
</body>
</html>
`;
}

function escapeHtml(text) {
    return String(text)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");
}

function outName(graph, dataFile) {
    if (graph.id) {
        return `${graph.id}.html`;
    }
    return path.basename(dataFile, path.extname(dataFile)) + ".html";
}

const inputs = process.argv.slice(2);
const files =
    inputs.length > 0
        ? inputs
        : fs
              .readdirSync(dataDir)
              .filter((name) => name.endsWith(".json"))
              .map((name) => path.join(dataDir, name));

if (files.length === 0) {
    console.error("No graph data files found.");
    process.exit(1);
}

for (const file of files) {
    const graph = JSON.parse(fs.readFileSync(file, "utf8"));
    const dest = path.join(graphsDir, outName(graph, file));
    fs.writeFileSync(dest, htmlPage(graph));
    console.log("wrote", path.relative(process.cwd(), dest));
}
