// AUTO-GENERATED by typescript-type-def

export namespace Babelfont {
    export type U16 = number;

    /**
     * A dictionary for internationalized strings.
     */
    export type I18NDictionary = Record<string, string>;
    export type F64 = number;
    export type F32 = number;
    export type JSONValue =
        | null
        | boolean
        | number
        | string
        | JSONValue[]
        | {
              [key: string]: JSONValue;
          };

    /**
     * A map for storing format-specific data.
     */
    export type FormatSpecific = Record<string, Babelfont.JSONValue>;

    /**
     * An axis in a variable font
     */
    export type Axis = {
        /**
         * Name of the axis
         */
        name: Babelfont.I18NDictionary;

        /**
         * 4-character tag of the axis
         */
        tag: string;

        /**
         * Unique identifier for the axis
         */
        id: string;

        /**
         * Minimum value of the axis in user space coordinates
         */
        min?: Babelfont.F64;

        /**
         * Maximum value of the axis in user space coordinates
         */
        max?: Babelfont.F64;

        /**
         * Default value of the axis in user space coordinates
         */
        default?: Babelfont.F64;

        /**
         * Mapping of user space coordinates to design space coordinates
         */
        map?: [Babelfont.F32, Babelfont.F32][];

        /**
         * Whether the axis is hidden in the font's user interface
         */
        hidden?: boolean;

        /**
         * Predefined values for the axis in user space coordinates
         */
        values?: Babelfont.F64[];

        /**
         * Format-specific data
         */
        formatspecific?: Babelfont.FormatSpecific;
    };

    /**
     * Name table values for a font or individual master
     */
    export type Names = {
        /**
         * Copyright notice (OpenType Name ID 0)
         */
        copyright?: Babelfont.I18NDictionary;

        /**
         * Font family name (OpenType Name ID 1)
         */
        family_name?: Babelfont.I18NDictionary;

        /**
         * Font Subfamily name (OpenType Name ID 2)
         */
        preferred_subfamily_name?: Babelfont.I18NDictionary;

        /**
         * Unique font identifier (OpenType Name ID 3)
         */
        unique_id?: Babelfont.I18NDictionary;

        /**
         * Full font name (OpenType Name ID 4)
         */
        full_name?: Babelfont.I18NDictionary;

        /**
         * Version string (OpenType Name ID 5)
         */
        version?: Babelfont.I18NDictionary;

        /**
         * PostScript name for the font (OpenType Name ID 6)
         */
        postscript_name?: Babelfont.I18NDictionary;

        /**
         * Trademark (OpenType Name ID 7)
         */
        trademark?: Babelfont.I18NDictionary;

        /**
         * Manufacturer Name (OpenType Name ID 8)
         */
        manufacturer?: Babelfont.I18NDictionary;

        /**
         * Designer. (Name of the designer of the typeface.) (OpenType Name ID 9)
         */
        designer?: Babelfont.I18NDictionary;

        /**
         * Description. (Description of the typeface.) (OpenType Name ID 10)
         */
        description?: Babelfont.I18NDictionary;

        /**
         * URL of Vendor. URL of font vendor (with protocol, e.g., http://, ftp://). (OpenType Name ID 11)
         */
        manufacturer_url?: Babelfont.I18NDictionary;

        /**
         * URL of Designer. URL of typeface designer (with protocol, e.g., http://, ftp://). (OpenType Name ID 12)
         */
        designer_url?: Babelfont.I18NDictionary;

        /**
         * License Description. Description of the license or licenses under which the font is provided. (OpenType Name ID 13)
         */
        license?: Babelfont.I18NDictionary;

        /**
         * License Info URL. URL where additional licensing information can be found. (OpenType Name ID 14)
         */
        license_url?: Babelfont.I18NDictionary;

        /**
         * Typographic Family name. (OpenType Name ID 16)
         */
        typographic_family?: Babelfont.I18NDictionary;

        /**
         * Typographic Subfamily name. (OpenType Name ID 17)
         */
        typographic_subfamily?: Babelfont.I18NDictionary;

        /**
         * Compatible Full (Macintosh only). (OpenType Name ID 18)
         */
        compatible_full_name?: Babelfont.I18NDictionary;

        /**
         * Sample text. (OpenType Name ID 19)
         */
        sample_text?: Babelfont.I18NDictionary;

        /**
         * PostScript CID findfont name. (OpenType Name ID 20)
         */
        postscript_cid_name?: Babelfont.I18NDictionary;

        /**
         * WWS Family Name. (OpenType Name ID 21)
         */
        wws_family_name?: Babelfont.I18NDictionary;

        /**
         * WWS Subfamily Name. (OpenType Name ID 22)
         */
        wws_subfamily_name?: Babelfont.I18NDictionary;

        /**
         * Variations PostScript Name Prefix. (OpenType Name ID 25)
         */
        variations_postscript_name_prefix?: Babelfont.I18NDictionary;
    };

    /**
     * A font instance
     */
    export type Instance = {
        /**
         * Unique identifier for the instance
         *
         * Should be unique within the design space; usually a UUID.
         */
        id: string;

        /**
         * Name of the instance
         */
        name: Babelfont.I18NDictionary;

        /**
         * Location of the instance in design space coordinates
         */
        location?: Record<string, Babelfont.F32>;

        /**
         * Any custom names for the instance if it is exported as a static font
         */
        custom_names: Babelfont.Names;

        /**
         * Whether the instance represents an export of a variable font
         */
        variable?: boolean;

        /**
         * Name of the linked style for style linking (e.g., "Bold Italic" links to "Bold" and "Italic")
         */
        linked_style?: string;

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * A position in 2D space, with an optional angle
     */
    export type Position = {
        /**
         * X coordinate
         */
        x: Babelfont.F32;

        /**
         * Y coordinate
         */
        y: Babelfont.F32;

        /**
         * Angle in degrees
         */
        angle?: Babelfont.F32;
    };
    export type I32 = number;
    export type Color = {
        r: Babelfont.I32;
        g: Babelfont.I32;
        b: Babelfont.I32;
        a: Babelfont.I32;
    };

    /**
     * A guideline in the font, whether at master or layer level
     */
    export type Guide = {
        /**
         * Position of the guideline
         */
        pos: Babelfont.Position;

        /**
         * Optional name of the guideline
         */
        name?: string;

        /**
         * Optional color of the guideline
         */
        color?: Babelfont.Color;

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };
    export type I16 = number;
    export type U32 = number;
    export type U8 = number;

    /**
     * A scalar value in an OpenType table
     */
    export type OTScalar =
        | {
              /**
               * String value
               */
              StringType: string;
          }
        | {
              /**
               * Boolean value
               */
              Bool: boolean;
          }
        | {
              /**
               * Unsigned integer value
               */
              Unsigned: Babelfont.U32;
          }
        | {
              /**
               * Signed integer value
               */
              Signed: Babelfont.I32;
          }
        | {
              /**
               * Floating-point value
               */
              Float: Babelfont.F32;
          }
        | {
              /**
               * Bit field value
               */
              BitField: Babelfont.U8[];
          }
        | {
              /**
               * Array of floating-point values
               */
              Array: Babelfont.F64[];
          };
    export type OTValue = {
        table: string;
        field: string;
        value: Babelfont.OTScalar;
    };

    /**
     * A master/source font in a design space
     */
    export type Master = {
        /**
         * Name of the master
         */
        name: Babelfont.I18NDictionary;

        /**
         * Unique identifier for the master (usually a UUID)
         */
        id: string;

        /**
         * Location of the master in design space coordinates
         */
        location?: Record<string, Babelfont.F32>;

        /**
         * Global guidelines associated with the master
         */
        guides?: Babelfont.Guide[];

        /**
         * Master-specific metrics
         */
        metrics: Record<string, Babelfont.I32>;

        /**
         * Kerning for this master.
         *
         * (Kerning pairs are (left glyph name, right glyph name) -> value)
         * Groups are represented as `@<groupname>`; whether they are first or second
         * groups is determined by position in the tuple.
         */
        kerning: Record<string, Record<string, Babelfont.I16>>; // Except it isn't!

        /**
         * Custom OpenType values for this master
         */
        custom_ot_values?: Babelfont.OTValue[];

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * The category of a glyph
     */
    export type GlyphCategory =
        /**
         * A base glyph
         */
        | 'Base'
        /**
         * A mark glyph
         */
        | 'Mark'
        /**
         * An unknown / un-set category
         */
        | 'Unknown'
        /**
         * A ligature glyph
         */
        | 'Ligature';

    /**
     * The type of a layer in relation to masters
     */
    export type LayerType =
        | {
              /**
               * A default layer for a master
               */
              DefaultForMaster: string;
          }
        | {
              /**
               * A layer associated with a master but not the default
               */
              AssociatedWithMaster: string;
          }
        /**
         * A free-floating layer not associated with any master
         */
        | 'FreeFloating';

    /**
     * A component in a glyph
     */
    export type Component = {
        /**
         * The referenced glyph name
         */
        reference: string;

        /**
         * The transformation applied to the component
         */
        transform?: Babelfont.F32[];

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * Types of nodes in a glyph outline
     */
    export type NodeType =
        /**
         * Move to a new position without drawing (only defined for open contours)
         */
        | 'Move'
        /**
         * Draw a straight line to this node
         */
        | 'Line'
        /**
         * Cubic Bézier curve control node (off-curve)
         */
        | 'OffCurve'
        /**
         * Draw a cubic Bézier curve to this node
         */
        | 'Curve'
        /**
         * Draw a quadratic Bézier curve to this node
         */
        | 'QCurve';

    /**
     * A node in a glyph outline
     */
    export type Node = {
        /**
         * The x-coordinate of the node
         */
        x: Babelfont.F64;

        /**
         * The y-coordinate of the node
         */
        y: Babelfont.F64;

        /**
         * The type of the node
         */
        nodetype: Babelfont.NodeType;

        /**
         * Whether the node is smooth
         */
        smooth?: boolean;
    };

    /**
     * A path in a glyph
     */
    export type Path = {
        /**
         * A list of nodes in the path
         */
        nodes: Babelfont.Node[];

        /**
         * Whether the path is closed
         */
        closed: boolean;

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * A shape in a glyph, either a component or a path
     */
    export type Shape =
        | {
              /**
               * A component in a glyph
               */
              Component: Babelfont.Component;
          }
        | {
              /**
               * A path in a glyph
               */
              Path: Babelfont.Path;
          };

    /**
     * An anchor point in a glyph
     */
    export type Anchor = {
        /**
         * X coordinate
         */
        x: Babelfont.F64;

        /**
         * Y coordinate
         */
        y: Babelfont.F64;

        /**
         * Name of the anchor
         */
        name?: string;

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * A layer of a glyph in a font
     */
    export type Layer = {
        /**
         * The advance width of the layer
         */
        width: Babelfont.F32;

        /**
         * The name of the layer
         */
        name?: string;

        /**
         * The ID of the layer
         */
        id?: string;

        /**
         * The relationship between this layer and a master, if any
         */
        master?: Babelfont.LayerType;

        /**
         * Guidelines in the layer
         */
        guides?: Babelfont.Guide[];

        /**
         * Shapes (paths and components) in the layer
         */
        shapes?: Babelfont.Shape[];

        /**
         * Anchors in the layer
         */
        anchors?: Babelfont.Anchor[];

        /**
         * The color of the layer
         */
        color?: Babelfont.Color;

        /**
         * The index of the layer in a color font
         */
        layer_index?: Babelfont.I32;

        /**
         * Whether this layer is a background layer
         */
        is_background?: boolean;

        /**
         * The ID of the background layer for this layer, if any
         */
        background_layer_id?: string;

        /**
         * The location of the layer in design space, if it is not at the default location for a master
         */
        location?: Record<string, Babelfont.F32>;

        /**
         * Format-specific data for the layer
         */
        format_specific?: Babelfont.FormatSpecific;
    };

    /**
     * Direction of text flow
     */
    export type Direction =
        /**
         * Left to right text flow
         */
        | 'LeftToRight'
        /**
         * Right to left text flow
         */
        | 'RightToLeft'
        /**
         * Top to bottom text flow
         */
        | 'TopToBottom';

    /**
     * A glyph in the font
     */
    export type Glyph = {
        /**
         * The name of the glyph
         */
        name: string;

        /**
         * The production name of the glyph, if any
         */
        production_name?: string;

        /**
         * The category of the glyph
         */
        category: Babelfont.GlyphCategory;

        /**
         * Unicode codepoints assigned to the glyph
         */
        codepoints?: Babelfont.U32[];

        /**
         * The layers in the glyph
         *
         * These include background layers, design-only layers, etc. as well as
         * the main master and location-specific layers.
         */
        layers?: Babelfont.Layer[];

        /**
         * Whether the glyph is exported
         */
        exported?: boolean;

        /**
         * The writing direction of the glyph, if any
         */
        direction?: Babelfont.Direction;

        /**
         * Format-specific data
         */
        formatspecific?: Babelfont.FormatSpecific;
    };

    /**
     * A list of glyphs in the font
     */
    export type GlyphList = Babelfont.Glyph[];

    /**
     * A representation of OpenType features, classes, and prefixes.
     */
    export type Features = {
        /**
         * Opentype classes
         *
         * The key should not start with @.
         */
        classes: Record<string, string>;

        /**
         * Opentype prefixes
         *
         * A dictionary of OpenType lookups and other feature code to be placed before features are defined.
         * The keys are user-defined names, the values are AFDKO feature code.
         */
        prefixes: Record<string, string>;

        /**
         * OpenType features
         *
         * A list of OpenType feature code, expressed as a tuple (feature tag, code).
         */
        features: [string, string][];

        /**
         * Include paths
         *
         * Paths to search for included feature files.
         */
        include_paths?: string[];
    };

    /**
     * A representation of a font source file
     */
    export type Font = {
        /**
         * Units per em
         */
        upm: Babelfont.U16;

        /**
         * Font version as (major, minor)
         */
        version: [Babelfont.U16, Babelfont.U16];

        /**
         * A list of axes, in the case of variable/multiple master font.
         *
         * May be empty.
         */
        axes?: Babelfont.Axis[];

        /**
         * A list of named/static instances
         */
        instances?: Babelfont.Instance[];

        /**
         * A list of the font's masters
         */
        masters?: Babelfont.Master[];

        /**
         * A list of the font's glyphs
         */
        glyphs: Babelfont.GlyphList;

        /**
         * An optional note about the font
         */
        note?: string;

        /**
         * The font's creation date
         */
        date: string;

        /**
         * The font's naming information
         */
        names: Babelfont.Names;

        /**
         * Any values to be placed in OpenType tables on export to override defaults
         *
         * These must be font-wide. Metrics which may vary by master should be placed in the `metrics` field of a Master
         */
        custom_ot_values?: Babelfont.OTValue[];

        /**
         * A map of Unicode Variation Sequences to glyph names
         */
        variation_sequences?: Record<
            Babelfont.U32,
            Record<Babelfont.U32, string> // Except it isn't.
        >;

        /**
         * A representation of the font's OpenType features
         */
        features: Babelfont.Features;

        /**
         * A dictionary of kerning groups
         *
         * The key is the group name and the value is a list of glyph names in the group
         * Group names are *not* prefixed with "@" here
         */
        first_kern_groups?: Record<string, string[]>;

        /**
         *
         * The key is the group name and the value is a list of glyph names in the group
         * Group names are *not* prefixed with "@" here
         */
        second_kern_groups?: Record<string, string[]>;

        /**
         * Format-specific data
         */
        format_specific?: Babelfont.FormatSpecific;

        /**
         * The source file path, if any, from which this font was loaded
         */
        source: string | null;
    };
}

export default Babelfont;
